name: build
on:
  push:
    branches: [ main ]
    paths-ignore:
    - '.**'
    - 'LICENSE'
    - 'README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - '.**'
    - 'LICENSE'
    - 'README.md'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Build
      run: |
        docker build .
