name: Release
on:
  release:
    types: [published]

jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:
    - name: Set ENV for 'Create Tag'
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> ${GITHUB_ENV}

    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.17'
        check-latest: true

    - name: Download dependency
      run: go mod download

    - name: Build
      run: |
        # spread the work across 2 processes
        build1=$!
        go run _script/build.go aliyun notify
        build2=$!
        go run _script/build.go tencent

        wait $build1
        wait $build2

    - name: Upload Assets
      run: |
        gh release upload ${{ env.VERSION }} *.zip --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
